# Generated by Django 3.2.1 on 2021-07-04 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210704_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 15, 39, 5, 18522)),
        ),
    ]
