# Generated by Django 3.2.1 on 2021-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
